/* ══════════════════════════════════════════════════════════════════
 * COFIATRADING — AUTH / CREDENTIALS / PROVIDERS PROOF LEDGER
 * ────────────────────────────────────────────────────────────────────
 * Source de vérité de l'audit auth COFIATRADING (verdict utilisateur).
 * Règle NO-FALSE-GREEN (§7 / §35) : un GREEN/LIVE n'apparaît QUE s'il a une
 * `proof` sourçable réelle. Les credentials présents mais non re-testés
 * restent en AMBER_REVERIFY (statusSource "config"), JAMAIS GREEN.
 *
 * Types : SSOT = `@/types/cofiatWorld.types`.
 * source_tag: COFIAT_AUTH_PROOF_LEDGER_V1_20260531
 * ════════════════════════════════════════════════════════════════ */

import type { AuthLedgerItem } from "@/types/cofiatWorld.types";

/**
 * Ledger d'auth canonique — transcription verbatim du verdict d'audit Erwin.
 * Aucun GREEN inventé : chaque GREEN/LIVE porte sa preuve réelle ; chaque
 * AMBER/OPTIONAL/ADAPTER_MISSING porte son blocker et/ou son fallback.
 */
export const cofiatAuthProofLedger: AuthLedgerItem[] = [
  // ─────────────────────────────────────────────────────────────────
  // CRITICAL — GREEN / LIVE (statusSource: "user_audit", preuve réelle)
  // ─────────────────────────────────────────────────────────────────
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    provider: "elevenlabs",
    category: "voice",
    status: "GREEN",
    statusSource: "user_audit",
    criticality: "critical",
    proof: "health key_present:true",
    greenCondition: "health endpoint répond key_present:true",
  },
  {
    id: "imagen-3-vertex",
    name: "Imagen 3 (Vertex)",
    provider: "imagen3-vertex",
    category: "image",
    status: "GREEN",
    statusSource: "user_audit",
    criticality: "critical",
    proof: "auth_ok projet cof-trading-prod",
    greenCondition: "auth_ok sur le projet cof-trading-prod",
  },
  {
    id: "veo-vertex",
    name: "Veo (Vertex)",
    provider: "veo-vertex",
    category: "video",
    status: "GREEN",
    statusSource: "user_audit",
    criticality: "critical",
    proof: "auth_ok",
    greenCondition: "auth_ok Vertex Veo",
  },
  {
    id: "hedra",
    name: "Hedra",
    provider: "hedra",
    category: "lipsync",
    status: "GREEN",
    statusSource: "user_audit",
    criticality: "critical",
    proof: "health key_present:true",
    greenCondition: "health endpoint répond key_present:true",
  },
  {
    id: "stripe",
    name: "Stripe",
    provider: "stripe",
    category: "revenue",
    status: "GREEN",
    statusSource: "user_audit",
    criticality: "critical",
    proof: "6 subs actifs / 6 matchés, sync 84s",
    greenCondition: "6 subscriptions actifs matchés, sync < ~84s",
  },
  {
    id: "telegram",
    name: "Telegram CRM",
    provider: "telegram",
    category: "crm",
    status: "GREEN",
    statusSource: "user_audit",
    criticality: "critical",
    proof: "bot ironcofbot, token_present, admin",
    greenCondition: "bot ironcofbot token_present + droits admin",
  },
  {
    id: "rithmic",
    name: "Rithmic",
    provider: "rithmic",
    category: "data",
    status: "LIVE",
    statusSource: "user_audit",
    criticality: "critical",
    proof: "rithmic-apex, heartbeat 4.4s, LIVE",
    greenCondition: "connexion rithmic-apex LIVE, heartbeat ~4.4s",
  },
  {
    id: "openrouter-gemini",
    name: "OpenRouter (Gemini)",
    provider: "openrouter-gemini",
    category: "llm",
    status: "GREEN",
    statusSource: "user_audit",
    criticality: "critical",
    proof: "Iron 110 envois/30j",
    greenCondition: "Iron route via OpenRouter-Gemini (110 envois/30j)",
  },
  {
    id: "cellxpert",
    name: "CellXpert",
    provider: "cellxpert",
    category: "broker",
    status: "GREEN",
    statusSource: "user_audit",
    criticality: "critical",
    proof: "$2.11M tracké, 6889 clients",
    greenCondition: "tracking broker actif ($2.11M, 6889 clients)",
  },

  // ─────────────────────────────────────────────────────────────────
  // REVERIFY — important, preuve périmée / session, à re-vérifier
  // ─────────────────────────────────────────────────────────────────
  {
    id: "meta-graph",
    name: "Meta Graph",
    provider: "meta-graph",
    category: "crm",
    status: "AMBER_REVERIFY",
    statusSource: "user_audit",
    criticality: "important",
    blocker: "token présent+refreshed, expire 60j, curl live refusé",
    greenCondition: "curl live Graph API répond 200 avec le token refreshed",
  },
  {
    id: "luma",
    name: "Luma",
    provider: "luma",
    category: "video",
    status: "AMBER_REPAIR",
    statusSource: "user_audit",
    criticality: "important",
    blocker: "cookie présent, retrieval cassé 2026-05-30",
    greenCondition: "retrieval Luma récupère un MP4 réel via la session cookie",
  },
  {
    id: "suno",
    name: "Suno",
    provider: "suno",
    category: "content",
    status: "AMBER_SESSION",
    statusSource: "user_audit",
    criticality: "important",
    blocker: "cookie session auto-expire",
    greenCondition: "cookie session Suno valide et stable (non auto-expiré)",
  },

  // ─────────────────────────────────────────────────────────────────
  // OPTIONAL — non bloquant, couvert par un fallback réel
  // ─────────────────────────────────────────────────────────────────
  {
    id: "perplexity-api",
    name: "Perplexity API",
    provider: "perplexity-api",
    category: "search",
    status: "ADAPTER_MISSING",
    statusSource: "user_audit",
    criticality: "optional",
    coveredBy: ["perplexity-desktop"],
    blocker: "Console IA adapter depends on API-only path",
    nextAction: "wire fallback chain",
    greenCondition: "fallback chain câblée vers perplexity-desktop (ou clé API présente)",
  },
  {
    id: "ideogram-api",
    name: "Ideogram API",
    provider: "ideogram-api",
    category: "image",
    status: "OPTIONAL_COVERED",
    statusSource: "user_audit",
    criticality: "optional",
    coveredBy: ["imagen-3-vertex"],
    greenCondition: "couvert par imagen-3-vertex (ou clé Ideogram présente)",
  },
  {
    id: "canva-api",
    name: "Canva API",
    provider: "canva-api",
    category: "design",
    status: "OPTIONAL_COVERED",
    statusSource: "user_audit",
    criticality: "optional",
    coveredBy: ["paperclip", "brand-pack-100"],
    greenCondition: "couvert par paperclip + brand-pack-100 (ou clé Canva présente)",
  },

  // ─────────────────────────────────────────────────────────────────
  // PRESENT-NOT-RETESTED — credentials présents, non re-testés
  // statusSource "config", criticality "important", AMBER_REVERIFY
  // ─────────────────────────────────────────────────────────────────
  {
    id: "notion",
    name: "Notion",
    provider: "notion",
    category: "ops",
    status: "AMBER_REVERIFY",
    statusSource: "config",
    criticality: "important",
    blocker: "credential présent mais non re-testé",
    greenCondition: "re-probe live répond 200 avec le credential présent",
  },
  {
    id: "linear",
    name: "Linear",
    provider: "linear",
    category: "ops",
    status: "AMBER_REVERIFY",
    statusSource: "config",
    criticality: "important",
    blocker: "credential présent mais non re-testé",
    greenCondition: "re-probe live répond 200 avec le credential présent",
  },
  {
    id: "resend",
    name: "Resend",
    provider: "resend",
    category: "broadcast",
    status: "AMBER_REVERIFY",
    statusSource: "config",
    criticality: "important",
    blocker: "credential présent mais non re-testé",
    greenCondition: "re-probe live répond 200 avec le credential présent",
  },
  {
    id: "vercel",
    name: "Vercel",
    provider: "vercel",
    category: "infra",
    status: "AMBER_REVERIFY",
    statusSource: "config",
    criticality: "important",
    blocker: "credential présent mais non re-testé",
    greenCondition: "re-probe live répond 200 avec le credential présent",
  },
  {
    id: "supabase",
    name: "Supabase",
    provider: "supabase",
    category: "infra",
    status: "AMBER_REVERIFY",
    statusSource: "config",
    criticality: "important",
    blocker: "credential présent mais non re-testé",
    greenCondition: "re-probe live répond 200 avec le credential présent",
  },
  {
    id: "n8n",
    name: "n8n",
    provider: "n8n",
    category: "ops",
    status: "AMBER_REVERIFY",
    statusSource: "config",
    criticality: "important",
    blocker: "credential présent mais non re-testé",
    greenCondition: "re-probe live répond 200 avec le credential présent",
  },
  {
    id: "github",
    name: "GitHub",
    provider: "github",
    category: "infra",
    status: "AMBER_REVERIFY",
    statusSource: "config",
    criticality: "important",
    blocker: "credential présent mais non re-testé",
    greenCondition: "re-probe live répond 200 avec le credential présent",
  },
  {
    id: "meta-whatsapp",
    name: "Meta WhatsApp",
    provider: "meta-whatsapp",
    category: "broadcast",
    status: "AMBER_REVERIFY",
    statusSource: "config",
    criticality: "important",
    blocker: "credential présent mais non re-testé",
    greenCondition: "re-probe live répond 200 avec le credential présent",
  },
  {
    id: "twilio",
    name: "Twilio",
    provider: "twilio",
    category: "broadcast",
    status: "AMBER_REVERIFY",
    statusSource: "config",
    criticality: "important",
    blocker: "credential présent mais non re-testé",
    greenCondition: "re-probe live répond 200 avec le credential présent",
  },
  {
    id: "pexels",
    name: "Pexels",
    provider: "pexels",
    category: "content",
    status: "AMBER_REVERIFY",
    statusSource: "config",
    criticality: "important",
    blocker: "credential présent mais non re-testé",
    greenCondition: "re-probe live répond 200 avec le credential présent",
  },
  {
    id: "pixabay",
    name: "Pixabay",
    provider: "pixabay",
    category: "content",
    status: "AMBER_REVERIFY",
    statusSource: "config",
    criticality: "important",
    blocker: "credential présent mais non re-testé",
    greenCondition: "re-probe live répond 200 avec le credential présent",
  },
  {
    id: "unsplash",
    name: "Unsplash",
    provider: "unsplash",
    category: "content",
    status: "AMBER_REVERIFY",
    statusSource: "config",
    criticality: "important",
    blocker: "credential présent mais non re-testé",
    greenCondition: "re-probe live répond 200 avec le credential présent",
  },
  {
    id: "freesound",
    name: "Freesound",
    provider: "freesound",
    category: "content",
    status: "AMBER_REVERIFY",
    statusSource: "config",
    criticality: "important",
    blocker: "credential présent mais non re-testé",
    greenCondition: "re-probe live répond 200 avec le credential présent",
  },
  {
    id: "runway",
    name: "Runway",
    provider: "runway",
    category: "video",
    status: "AMBER_REVERIFY",
    statusSource: "config",
    criticality: "important",
    blocker: "credential présent mais non re-testé",
    greenCondition: "re-probe live répond 200 avec le credential présent",
  },
];
